---
title: "MY WILD THING REPORT"
author: "YOUR TEAM NAME AND MEMBERS HERE"
format: html
---

## Introduction

The whale shark is the largest fish in existence, with a maximum size of approximately 1200 centimeters (12 meters). The whale shark has a distinctive physical appearance. It is typically blue-grey or brownish in color with a pattern of white spots and vertical lines on its body. The mouth is unique, bearing about 300 rows of minute teeth in each jaw. This mouth structure is adapted for filter feeding. They are found in oceanic waters, typically at depths of up to 1000 meters. However, they seasonally come close to inshore areas, especially at plankton-rich locations like the Ningaloo Reef. They prefer areas with water temperatures ranging from 21 to 25 degrees Celsius, where plankton is abundant. They are also found in some part of Northern Australia. The Ningaloo Reef, located along the Western Australian coastline, is one of the most famous places in the world to encounter whale sharks. The reef provides a unique and important habitat for these gentle giants. Whale sharks are known to migrate to the Ningaloo Reef during specific times of the year, usually between March and July. This migration is associated with the availability of plankton and other food sources in the area. Whale shark tourism is a significant industry in Western Australia, where tourists have the opportunity to swim with these massive creatures in their natural habitat. Strict regulations are in place to ensure the protection of the sharks and the reef ecosystem. Whale sharks are generally known to be active swimmers, and their activity can vary throughout the day and night. They do not exhibit diurnal (daytime) or seasonal (summer/winter) patterns of activity in the same way that some other species do. Research on this species is still in motion but there is no concrete information about their population trend. Apparently, in some parts of the world these sharks were being hunted for exporting their meat and saw a crucial declining rate. Hence, Conservation measures, including protections and regulations, are being implemented to safeguard this species in Australia and many other countries.

Expectations:

- We expect to observe seasonal patterns in whale shark sightings, with higher occurrences during specific months that coincide with plankton blooms or favorable water conditions.
- We expect to see differences in the frequency of sightings between coastal areas and open ocean regions, indicating habitat preferences.
- We can find evidence of population trends, such as increasing or decreasing numbers of whale sharks, in certain areas or regions.
- If we have information about the size of sharks, We expect to gain insights into their growth and reproduction patterns.
- We anticipate finding correlations between environmental factors, such as sea surface temperature and ocean currents, and the presence or absence of whale sharks in specific locations.

Whale Shark (Rhincodon typus) is the largest of all fishes alive. It may grow up to 18 metres (m) in length, but commonly seen between 4 m to 12 m. They are found on all the tropical oceans of the world. In Australia, it is known primarily in northern Western Australia, the Northern Territory, and Queensland. They are easy to distinguish by their white spotted colouration, and they are notoriously very gentle to humans. There is actually a big ecotourism for the chance to swim with them, which usually occur during April to July where this big fish congregate in the Ningaloo Marine Park of Western Australia. In terms of the diet, they feed on plankton, small crustaceans, squid, and fishes. The main feature of their food processing tools are their filtering screens on the gills and their tiny, more than 300 hooked teeth in both jaws. Sadly, now, their status is an endangered species due to massive hunt of parts of their bodies.

Questions:
1.	We expect to find the most occurrences in the middle of ocean. 
2.	We expect to see the most occurrences during fall months.
3.	We expect to spot the most occurrences in the northern Western Australia.
4.	We expect to observe declining occurrences up to this year (2023).
5.	We expect to detect ….


## Data description

<!--
2. Download all the occurrence records from the Atlas of Living Australia, ideally scripted using the `atlas_occurrences()` function from the `galah` package. Make sure you include date, time, collector identification details. Save this into a `data-raw` folder in your repo.
-->

## Initial data analysis

<!--
3. Perform a data quality check, and then go ahead and clean the data, saving only the wild sightings. Save the resulting data in a `data` folder as an `WILD_THING_COMMON_NAME.rda` file, so that any special variable types are clearly available. (Replace `WILD_THING_COMMON_NAME` with lower case common name of your assigned wild thing.) *Note:* Some are museum or historical records or live in an animal sanctuary or zoo, which do not truly capture their wild behaviour. Downloading the event information (`galah_select(group = "event")`) can help identify wild sightings.

Weather data pre-processing here too.
-->

## Exploratory data analysis

<!--
4. Make plots of the data to check each of your expectations, and report what you learn. *Note:* This might also be a place where visual inference methods *may* be useful to determine if what is seen agrees or disputes what you expected. 

Weather data exploration here too.
-->

## Summary 

## References
Department of Fisheries, Government of Western Australia. (2011, September). Fisheries Fact Sheet: Whale Shark. https://www.fish.wa.gov.au/documents/recreational_fishing/fact_sheets/fact_sheet_whale_shark.pdf
 
McGrouther, Mark. (2022, October). Whale Shark, Rhincodon typus (Smith, 1828). Australian Museum. https://australian.museum/learn/animals/fishes/whale-shark-rhincodon-typus-smith-1828/

Britannica. (2023, August). Whale Shark. Britannica. https://www.britannica.com/animal/whale-shark


